#!/usr/bin/env zsh

DOTFILES_DIR="$(dirname ${0:A})"

cat <<END > "$HOME/.zsh_dotfiles_init"
# Warning: This file is auto-generated by ${0:A}.
# It will be overwritten as soon as ${0:A} is run again.
export DOTFILES_DIR=$DOTFILES_DIR
export ZSH=${ZSH:="$HOME/.oh-my-zsh"}
END

$DOTFILES_DIR/zsh/install.zsh
$DOTFILES_DIR/vim/install.zsh
$DOTFILES_DIR/tmux/install.zsh
$DOTFILES_DIR/leiningen/install.zsh
$DOTFILES_DIR/git/install.zsh
