# If TERMINAL_EMULATOR equals 'JetBrains-JediTerm' we are inside IntelliJ IDEA
# or another Jetbrains IDE. In this case we don't want to start TMUX, as this
# leads to display errors.
if [ "$TERMINAL_EMULATOR" != "JetBrains-JediTerm" ] && [ "$TERM_PROGRAM" != "vscode" ] && command -v tmux>/dev/null; then
  if [[ ! $TERM =~ tmux ]] && [ -z $TMUX ]; then
    export TERM=tmux-256color
    export TMUX_DEFAULT_SESSION="default"
    # Create a new session if it does not exists or attach
    # to the existing one
    exec tmux new-session -A -s $TMUX_DEFAULT_SESSION
  fi
fi
