## Enable for profiling. Call zprof to see results
## See https://github.com/zplug/zplug/issues/368 for some hints
# zmodload zsh/zprof

if [ -f "$HOME/.zsh_dotfiles_init" ]
then
    source "$HOME/.zsh_dotfiles_init"

    if [ -n "$NVIM_LISTEN_ADDRESS" ] && [ -n "$NEOVIM_NVR" ]
    then
        export EDITOR="$NEOVIM_NVR -cc split --remote-wait +'set bufhidden=wipe'"
        export VISUAL="$EDITOR"
    else
        export EDITOR="nvim"
        export VISUAL="$EDITOR"
    fi
else
    echo "Could not find '$HOME/.zsh_dotfiles_init'!"
    echo "Execute over-all install script!"
fi
