## Enable for profiling. Call zprof to see results
## See https://github.com/zplug/zplug/issues/368 for some hints
# zmodload zsh/zprof

if [ -f "$HOME/.zsh_dotfiles_init" ]
then
    source "$HOME/.zsh_dotfiles_init"
else
    echo "Could not find '$HOME/.zsh_dotfiles_init'!"
    echo "Execute over-all install script!"
fi

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
