if [ -f "$HOME/.zsh_dotfiles_init" ]; then
    source "$HOME/.zsh_dotfiles_init"
else
    echo "Warning: could not find $HOME/.zsh_dotfiles_init"
fi

# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Make '..' work like 'cd ..'
setopt autocd

source ~/.zplug/init.zsh

zplug "zplug/zplug", hook-build:"zplug --self-manage"

zplug "lib/clipboard", from:oh-my-zsh
zplug "lib/compfix", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh
zplug "lib/correction", from:oh-my-zsh
zplug "lib/directories", from:oh-my-zsh
zplug "lib/functions", from:oh-my-zsh
zplug "lib/git", from:oh-my-zsh
zplug "lib/grep", from:oh-my-zsh
zplug "lib/history", from:oh-my-zsh
zplug "lib/key-bindings", from:oh-my-zsh
zplug "lib/spectrum", from:oh-my-zsh
zplug "lib/termsupport", from:oh-my-zsh
zplug "lib/theme-and-appearance", from:oh-my-zsh
zplug "zsh-users/zsh-autosuggestions"

zplug "dracula/zsh", as:theme

zplug "$DOTFILES_DIR/vim", from:local

# Load some plugin specific settings we don't want to clutter our main
# zshrc file with
for x in $(ls $DOTFILES_DIR/zsh/conf.d/*.zsh); do
    source "$x"
done

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
